[package]
name = "minibar"
description = "A mini progress bar crate for Rust"
version = "0.1.0"
authors = ["Anders Olsson <anders.e.olsson@gmail.com>"]
license = "MIT"
repository = "https://github.com/logaritmisk/minibar"
edition = "2018"

[dependencies]
bytesize = "1.0"
termion = "1.5"
